In [1]:
import numpy as np
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('../data/raw/loan_data.csv')

In [3]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
df.drop("Loan_ID" , axis=1 , inplace=True)

In [5]:
df.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['Married'].fillna(df["Married"].mode()[0], inplace=True)
df['Dependents'].fillna(df["Dependents"].mode()[0], inplace=True)
df["Self_Employed"].fillna(df["Self_Employed"].mode()[0], inplace=True)

In [7]:
df['Credit_History'].fillna(df["Credit_History"].mode()[0], inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0], inplace=True)

In [8]:
df['LoanAmount'].fillna(df['LoanAmount'].median(), inplace=True)

In [9]:
df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [10]:
df["Dependents"] = df["Dependents"].replace("3+",3)
df["Dependents"] = df["Dependents"].astype(int)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             614 non-null    object
 1   Married            614 non-null    object
 2   Dependents         614 non-null    int64
 3   Education          614 non-null    object
 4   Self_Employed      614 non-null    object
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         614 non-null    float64
 8   Loan_Amount_Term   614 non-null    float64
 9   Credit_History     614 non-null    float64
 10  Property_Area      614 non-null    object
 11  Loan_Status        614 non-null    object
dtypes: float64(4), int64(2), object(6)
memory usage: 57.7+ KB

In [12]:
df["Gender"] = df["Gender"].map({"Male":1, "Female":0})
df["Married"] = df["Married"].map({"Yes":1 , "No":0})
df["Education"] = df["Education"].map({"Graduate":1 , "Not Graduate":0})
df["Self_Employed"] = df["Self_Employed"].map({"Yes":1 , "No":0})
df['Loan_Status'] = df["Loan_Status"].map({'Y':1 , 'N':0})

In [13]:
df = pd.get_dummies(df, columns=['Property_Area'], drop_first=True)

In [14]:
df = df.astype(int)

In [15]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Property_Area_Semiurban,Property_Area_Urban
0,1,0,0,1,0,5849,0,128,360,1,1,0,1
1,1,1,1,1,0,4583,1508,128,360,1,0,0,0
2,1,1,0,1,1,3000,0,66,360,1,1,0,1
3,1,1,0,0,0,2583,2358,120,360,1,1,0,1
4,1,0,0,1,0,6000,0,141,360,1,1,0,1

In [16]:
df.to_csv("../data/processed/clean_data.csv", index=False)

# Data Preprocessing Summary

- Dropped unnecessary column (Loan_ID)
- Handled missing values using mode and median
- Fixed inconsistent values in Dependents
- Converted categorical data into numeric format
- Applied one-hot encoding for Property_Area
- Saved clean dataset for model training